# .goreleaser.yml
archive:
  format: binary
builds:
  - main: ./main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
git:
  short_hash: true
