version: 2
jobs:
  goreleaser:
    working_directory: /go/src/github.com/ovotech/aes-256-gcm-kms

    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout

      - run:
           name: goreleaser
           command: |
             export GITHUB_TOKEN=$GITHUB
             go get -u github.com/jessevdk/go-flags
             go get -u golang.org/x/oauth2/google
             go get -u google.golang.org/api/cloudkms/v1
             curl -sL https://git.io/goreleaser | bash

    filters:
      tags:
        only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      branches:
        ignore: /.*/

workflows:
  version: 2
  goreleaser_pipeline:
    jobs:
      - goreleaser:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
