version: 2
jobs:
  goreleaser:
    working_directory: /go/src/github.com/ovotech/aes-256-gcm-kms

    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout

      - run:
           name: goreleaser
           command: |
             export GITHUB_TOKEN=$GITHUB
             curl -sL https://git.io/goreleaser | bash

    filters:
      tags:
        only: /v[0-9]+(\.[0-9]+)*(-.*)*/

workflows:
  version: 2
  goreleaser_pipeline:
    jobs:
      - goreleaser:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
